package app

import (
	"log/slog"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/cors"
	sloghttp "github.com/samber/slog-http"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

type Registrar interface {
	Register(r chi.Router)
}

// NewRouter builds the HTTP handler. Public registrars mount directly under
// /api/v1; protected registrars mount inside a group guarded by authMiddleware.
func NewRouter(log *slog.Logger, authMiddleware func(http.Handler) http.Handler, public, protected []Registrar) http.Handler {
	r := chi.NewRouter()

	r.Use(middleware.RequestID)

	r.Use(cors.Handler(cors.Options{
		AllowedOrigins: []string{"http://localhost:8081"},
		AllowedMethods: []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowedHeaders: []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
		ExposedHeaders: []string{"Link"},
		// Required so the browser sends the HttpOnly refresh cookie on
		// login/refresh/logout. With credentials, AllowedOrigins must stay a
		// concrete origin (no "*" wildcard).
		AllowCredentials: true,
		MaxAge:           300,
	}))

	// chi's RequestID is the single source of truth for the request id, so we
	// disable slog-http's own id generation to avoid a duplicate field.
	logConfig := sloghttp.DefaultConfig()
	logConfig.WithRequestID = false
	// Don't log client IPs — they are PII in some jurisdictions and we have no
	// operational need for them here.
	logConfig.WithClientIP = false

	r.Use(sloghttp.Recovery)
	r.Use(sloghttp.NewWithConfig(log, logConfig))
	r.Use(injectRequestID)

	r.Get("/openapi.yaml", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "openapi.yaml")
	})

	r.Get("/docs/*", httpSwagger.Handler(
		httpSwagger.URL("/openapi.yaml"),
	))

	r.Route("/api/v1", func(r chi.Router) {
		for _, reg := range public {
			reg.Register(r)
		}

		r.Group(func(r chi.Router) {
			r.Use(authMiddleware)
			for _, reg := range protected {
				reg.Register(r)
			}
		})
	})

	return r
}

// injectRequestID surfaces the request ID generated by chi's middleware.RequestID:
// it adds the id to the slog-http log line as request_id and echoes it back to the
// client in the X-Request-Id response header for correlation. It must run after
// sloghttp.NewWithConfig, once the per-request log context exists.
func injectRequestID(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if id := middleware.GetReqID(r.Context()); id != "" {
			w.Header().Set(middleware.RequestIDHeader, id)
			sloghttp.AddCustomAttributes(r, slog.String("request_id", id))
		}
		next.ServeHTTP(w, r)
	})
}
