// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        uuid.UUID
	UserID    pgtype.UUID
	Action    string
	Metadata  []byte
	IpAddress *netip.Addr
	UserAgent *string
	CreatedAt time.Time
}

type LoginAttempt struct {
	ID        uuid.UUID
	Email     string
	IpAddress *netip.Addr
	Success   bool
	Reason    *string
	CreatedAt time.Time
}

type RefreshSession struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	UserAgent  *string
	IpAddress  *netip.Addr
	CreatedAt  time.Time
	ExpiresAt  time.Time
	RevokedAt  pgtype.Timestamptz
	ReplacedBy pgtype.UUID
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
