// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRefreshSessionByHash(ctx context.Context, tokenHash string) (RefreshSession, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error
	RevokeAndReplaceRefreshSession(ctx context.Context, arg RevokeAndReplaceRefreshSessionParams) error
	RevokeRefreshSession(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
